# nixpacks.toml

# Указываем язык программирования и его версию
[language]
name = "dotnet"
version = "8.0"

# Указываем пути к проекту и файлам
[project]
entry = "Puppy.csproj"  # замените на название вашего .csproj файла

# Указываем зависимости и инструкции для сборки
[dependencies]
commands = [
    "dotnet restore"  # восстанавливаем зависимости
]

# Инструкции для сборки проекта
[build]
commands = [
    "dotnet build --configuration Release --output out"  # сборка проекта в папку out
]

# Инструкции для запуска приложения
[start]
commands = [
    "dotnet out/Puppy.dll"  # замените на путь к собранному .dll файлу
]

# Дополнительные настройки
[env]
variables = {
    "ASPNETCORE_ENVIRONMENT" = "Production"
}
